"""
TrustLens Analyze Route (Phase 6 async refactor)

Flask 2.0+ supports async route handlers natively.
Hypercorn (ASGI) is required to honour the async semantics — the default
Werkzeug dev server is WSGI-only and would run the coroutine synchronously,
eliminating all concurrency gains.

Key changes from the synchronous version:
  1. `async def analyze()` — Flask detects the coroutine and schedules it properly
  2. `await download_image()` — single download replacing the previous double-call
  3. `await analyze_text_with_llm()` — no longer blocks the event loop
  4. `await compute_full_credibility()` — internally uses asyncio.gather for
     phases 2, 3, 4 concurrently

Phase execution order (cannot be fully parallelised):
  LLM text → must complete first (primaryClaim needed for fact-check)
  ↓
  asyncio.gather(fact-check, domain, image)  ← concurrently in Phase 6
  ↓
"""

import asyncio
import time
import re
from flask import Blueprint, request, jsonify
from pydantic import ValidationError
from app.models.schemas import AnalyzeRequest
from app.services.llm_analysis import analyze_text_with_llm, analyze_image_with_llm
from app.services.credibility_engine import compute_full_credibility
from app.services.image_metadata import analyze_image_metadata
from app.services.image_tracing import trace_image
from app.services.image_scoring import calculate_image_credibility
from app.services.analysis_storage_service import store_analysis, get_analysis_by_hash
from app.utils.fetch_image import download_image
from app.utils.hashing import hash_image, hash_text
from app.services.video_analysis import analyze_video_with_llm
from app.services.video.video_pipeline import process_video_text
from app.services.evidence.evidence_aggregator import aggregate_evidence
from app.services.evidence.evidence_verifier import verify_claim_with_evidence
from app.services.claim_validator import filter_and_normalize_claims
from app.services.claim_verification_service import (
    verify_all_claims,
    verify_all_claims_decomposed,
)
from app.services.claim_decomposition_service import decompose_claims
from app.services import job_registry

analyze_bp = Blueprint('analyze', __name__)

VALID_VERDICTS = ["Highly Reliable", "Reliable", "Likely Reliable", "Questionable", "High Risk"]


def normalize_verdict(verdict: str) -> str:
    if isinstance(verdict, str) and verdict in VALID_VERDICTS:
        return verdict
    return "High Risk"


# ---------------------------------------------------------------------------
# Cancel endpoint — called by the extension when the user dismisses the overlay
# ---------------------------------------------------------------------------
@analyze_bp.route('/cancel', methods=['POST'])
def cancel_analysis():
    """
    Cancel an in-flight analysis task identified by jobId.
    The jobId is generated by the extension client and sent with the
    original /api/analyze request.
    """
    data = request.get_json(silent=True) or {}
    job_id = data.get('jobId', '')
    if not job_id:
        return jsonify({"cancelled": False, "error": "Missing jobId"}), 400

    cancelled = job_registry.cancel(job_id)
    print(f"{'🛑' if cancelled else '⏭️'} [Cancel] job={job_id} cancelled={cancelled}")
    return jsonify({"cancelled": cancelled})


@analyze_bp.route('', methods=['GET'])
def get_analyze_info():
    return jsonify({
        "success": True,
        "message": "TrustLens Analyze API",
        "endpoint": "/api/analyze",
        "method": "POST",
        "description": "Analyze text and images for misinformation risk assessment",
        "requestBody": {
            "text": {"type": "string", "required": False, "minLength": 5},
            "imageUrl": {"type": "string", "required": False, "format": "url"},
        },
        "example": {
            "text": "This is a sample text to analyze for misinformation",
            "imageUrl": "https://example.com/image.jpg",
        },
    })


@analyze_bp.route('', methods=['POST'])
async def analyze():
    """
    Async POST handler — Flask 2.0+ schedules this as a coroutine.
    Requires Hypercorn (ASGI) to run concurrently.
    """
    _start = time.perf_counter()
    job_id: str | None = None

    try:
        print("📥 /api/analyze route hit")

        data = request.get_json()
        if not data:
            return jsonify({"success": False, "message": "Invalid JSON in request body"}), 400

        # Register this asyncio Task so the /cancel endpoint can stop it.
        job_id = data.get("jobId") or ""
        if job_id:
            current_task = asyncio.current_task()
            if current_task:
                job_registry.register(job_id, current_task)
                print(f"📋 [Job] Registered analysis task: {job_id}")

        try:
            validated_data = AnalyzeRequest(**data)
        except ValidationError as e:
            return jsonify({"success": False, "message": e.errors()[0]['msg']}), 400

        # ------------------------------------------------------------------ #
        # Step 1: Image download (single — was done twice in the sync version)
        # All image-based phases receive the same buffer from this one call.
        # ------------------------------------------------------------------ #
        image_buffer: bytes | None = None
        image_hash: str | None = None
        image_reused = False
        image_analysis: dict = {"status": "skipped"}

        if validated_data.imageUrl:
            try:
                print(f"🖼️ Fetching image: {validated_data.imageUrl}")
                dl = await download_image(validated_data.imageUrl)

                if dl.get("success") and dl.get("buffer"):
                    image_buffer = dl["buffer"]
                    image_hash = hash_image(image_buffer)
                    existing_image = get_analysis_by_hash(image_hash)

                    if existing_image:
                        print(f"♻️ Reusing cached image analysis for hash: {image_hash[:16]}...")
                        image_analysis = existing_image.get("analysis", {})
                        image_analysis["reused"] = True
                        image_reused = True
                    else:
                        # Legacy image pipeline (metadata, tracing, LLM image)
                        metadata, tracing, llm_image_result = {}, {}, {}
                        try:
                            metadata = analyze_image_metadata(image_buffer)
                            tracing  = trace_image(image_buffer)
                        except Exception as tech_err:
                            print(f"⚠️ Technical analysis error: {tech_err}")

                        try:
                            print("🎨 Starting LLM Image Analysis...")
                            llm_image_result = await analyze_image_with_llm(image_buffer, validated_data.text or "")
                            print(f"✅ LLM Image Analysis done")
                        except Exception as llm_err:
                            print(f"❌ LLM image analysis failed: {llm_err}")

                        ai_prob = llm_image_result.get("aiGeneratedProbability", 0)
                        credibility_result = calculate_image_credibility(metadata, tracing, ai_prob)
                        llm_score   = llm_image_result.get("credibilityScore", 100)
                        tech_score  = credibility_result["score"]
                        final_image_score = min(llm_score, tech_score)

                        final_image_verdict = normalize_verdict(
                            llm_image_result.get("verdict", credibility_result.get("verdict", "High Risk"))
                        )
                        if final_image_score < 40:
                            final_image_verdict = "High Risk"
                        elif final_image_score < 75:
                            final_image_verdict = "Questionable"

                        image_analysis = {
                            "status": "processed",
                            "metadata": metadata,
                            "tracing":  tracing,
                            "llmAnalysis": {
                                "riskLevel":            llm_image_result.get("riskLevel", "medium"),
                                "verdict":              normalize_verdict(llm_image_result.get("verdict")),
                                "credibilityScore":     llm_image_result.get("credibilityScore", 50),
                                "extractedText":        llm_image_result.get("extractedText", ""),
                                "textVerification":     llm_image_result.get("textVerification", ""),
                                "imageContent":         llm_image_result.get("imageContent", ""),
                                "conveyedMessage":      llm_image_result.get("conveyedMessage", ""),
                                "veracityCheck":        llm_image_result.get("veracityCheck", ""),
                                "explanation":          llm_image_result.get("explanation", ""),
                                "visualRedFlags":       llm_image_result.get("visualRedFlags", []),
                                "aiGeneratedProbability": llm_image_result.get("aiGeneratedProbability", 0),
                            } if llm_image_result else None,
                            "credibilityScore": final_image_score,
                            "verdict":          final_image_verdict,
                        }
                        store_analysis(image_hash, "image", image_analysis)
                else:
                    print(f"⚠️ Image download failed: {dl.get('error')}")
                    image_analysis = {"status": "skipped", "error": dl.get("error")}

            except Exception as e:
                print(f"❌ [Image Analysis] Unexpected error: {e}")
                image_analysis = {"status": "skipped", "error": str(e)}

        # ------------------------------------------------------------------ #
        # Step 2: Text analysis (Phase 1 — must complete before fact-check)
        # ------------------------------------------------------------------ #
        text_hash: str | None = None
        text_reused = False
        text_analysis: dict = {"status": "skipped"}

        if validated_data.text:
            text_hash = hash_text(validated_data.text)
            existing_text = get_analysis_by_hash(text_hash)

            if existing_text:
                print(f"♻️ Reusing cached text analysis for hash: {text_hash[:16]}...")
                text_analysis = existing_text.get("analysis", {})
                text_reused = True
            else:
                try:
                    print("✍️ Starting LLM Text Analysis...")
                    llm_result = await analyze_text_with_llm(validated_data.text)
                    print("✅ LLM Text Analysis complete")

                    semantic_score = llm_result.get("semanticScore", 50)
                    credibility_score = max(0, min(100, int(semantic_score)))
                    if credibility_score >= 75:
                        verdict, risk_level = "Reliable", "low"
                    elif credibility_score >= 40:
                        verdict, risk_level = "Questionable", "medium"
                    else:
                        verdict, risk_level = "High Risk", "high"

                    risk_keywords = list(
                        llm_result.get("manipulationIndicators", [])
                        + llm_result.get("riskFactors", [])
                    )[:20]

                    # --- Claim Validation & Normalisation ---
                    raw_claims = llm_result.get("keyClaims", [])
                    validated_claims = filter_and_normalize_claims(raw_claims)
                    print(f"✅ Claim validation: {len(raw_claims)} raw → {len(validated_claims)} valid")

                    text_analysis = {
                        "credibilityScore":  credibility_score,
                        "verdict":           normalize_verdict(verdict),
                        "riskLevel":         risk_level,
                        "riskKeywordsFound": risk_keywords,
                        "keyClaims":         validated_claims,
                        "validatedClaims":   validated_claims,
                        "explanation":       llm_result.get("reasoningSummary", ""),
                        "semantic": {
                            "semanticScore":          llm_result.get("semanticScore"),
                            "confidenceScore":        llm_result.get("confidenceScore"),
                            "primaryClaim":           llm_result.get("primaryClaim"),
                            "keyClaims":              validated_claims,
                            "manipulationIndicators": llm_result.get("manipulationIndicators", []),
                            "riskFactors":            llm_result.get("riskFactors", []),
                            "evidenceStrength":       llm_result.get("evidenceStrength"),
                            "reasoningSummary":       llm_result.get("reasoningSummary"),
                        },
                    }

                    # --- Empty-claims fallback ---
                    if not validated_claims:
                        print("⚠️ No valid claims found after filtering — applying empty-claim fallback")
                        text_analysis["noVerifiableClaims"] = True
                        text_analysis["explanation"] = (
                            "No verifiable factual claims were identified in the content. "
                            + text_analysis.get("explanation", "")
                        ).strip()
                        text_analysis["credibilityScore"] = min(credibility_score, 40)
                        text_analysis["semantic"]["evidenceStrength"] = "Weak"

                    # ---- Phase D: Claim Decomposition + Evidence Verification ----
                    # Stage 1 — Event Detection + Structuring + Query Normalization
                    # Stage 2 — Multi-query evidence retrieval + LLM verification
                    primary_claim = text_analysis["semantic"].get("primaryClaim")
                    claims_to_verify: list[str] = validated_claims or (
                        [primary_claim] if primary_claim else []
                    )

                    if claims_to_verify:
                        print(f"🔬 [Phase D] Decomposing {len(claims_to_verify)} claim(s) into event-level structures...")
                        decomposed = await decompose_claims(
                            claims_to_verify, 
                            context=validated_data.text or "",
                            primary_claim=primary_claim or ""
                        )
                        print(f"✅ [Phase D] Decomposition produced {len(decomposed)} structured claim(s)")

                        if decomposed:
                            # Use decomposed path: normalizedQueries → multi-query evidence
                            verified_claims_result, ks_score = await verify_all_claims_decomposed(decomposed)
                        else:
                            # Fallback: decomposition returned empty (all topic summaries rejected)
                            # Use the original validated claims directly
                            print("⚠️ [Phase D] Decomposition rejected all claims — falling back to direct verification")
                            verified_claims_result, ks_score = await verify_all_claims(claims_to_verify)

                        # Extract breaking news flags from the verified claims
                        is_breaking = any(c.get("isBreakingNews", False) for c in verified_claims_result)
                        breaking_sources = []
                        if is_breaking:
                            # Aggregate supporting publishers from all breaking claims
                            pub_sets = [set(c.get("trustedSourcesUsed", [])) for c in verified_claims_result if c.get("isBreakingNews")]
                            if pub_sets:
                                breaking_sources = list(set.union(*pub_sets))

                        text_analysis["structuredClaims"]   = decomposed
                        text_analysis["knowledgeVerification"] = {
                            "knowledgeSupportScore": ks_score,
                            "verifiedClaims":        verified_claims_result,
                            "breakingNewsDetected":  is_breaking,
                            "breakingNewsSources":   breaking_sources,
                        }
                        # Expose enriched keyClaims for API response
                        text_analysis["keyClaims"] = verified_claims_result
                        print(
                            f"✅ [Phase D] {len(verified_claims_result)} claim(s) verified. "
                            f"knowledgeSupportScore={ks_score:.4f}"
                        )
                    else:
                        print("⚠️ [Phase D] No claims available — skipping decomposition and evidence phase")

                    store_analysis(text_hash, "text", text_analysis)

                except Exception as e:
                    print(f"❌ LLM text analysis failed: {e}")
                    text_analysis = {"status": "skipped", "error": f"LLM text analysis failed: {e}"}
        else:
            print("📝 No text provided, skipping LLM text analysis")

        # ------------------------------------------------------------------ #
        # Step 2.5: Video Analysis
        # ------------------------------------------------------------------ #
        video_analysis: dict = {"status": "skipped"}
        video_hash: str | None = None
        video_reused = False

        if validated_data.videoUrl:
            video_hash = hash_text(validated_data.videoUrl)
            existing_video = get_analysis_by_hash(video_hash)

            if existing_video:
                print(f"♻️ Reusing cached video analysis...")
                video_analysis = existing_video.get("analysis", {})
                video_reused = True
            else:
                try:
                    # Sanity check: Ensure the URL contains a path indicating an actual post/video,
                    # not just a root domain or user profile (e.g. "https://www.instagram.com/")
                    valid_post_patterns = [
                        r"/status/", r"/reel/", r"/video/", r"/p/", r"/watch", 
                        r"/shorts/", r"/v/", r"/clip/"
                    ]
                    
                    is_valid_post = any(re.search(pattern, validated_data.videoUrl.lower()) for pattern in valid_post_patterns)
                    
                    if not is_valid_post:
                        print(f"⏩ Skipping video extraction: URL '{validated_data.videoUrl}' does not look like a specific video post")
                        video_analysis = {"status": "skipped", "error": "Not a valid video post URL"}
                    else:
                        print(f"📹 Starting multimodal video extraction for: {validated_data.videoUrl}")
                        # Step 1: Extract Audio Transcript & OCR Frames Concurrently
                        extraction_result = await process_video_text(validated_data.videoUrl)
    
                        if extraction_result.get("success"):
                            print(f"🤖 Starting LLM video analysis against Multimodal String...")
                            llm_video_result = await asyncio.to_thread(
                                analyze_video_with_llm,
                                extraction_result["combinedVideoText"],
                                validated_data.videoUrl,
                                validated_data.text or ""
                            )
                            # --- Claim Validation & Normalisation (Video) ---
                            raw_video_claims = llm_video_result.get("claimsIdentified", [])
                            validated_video_claims = filter_and_normalize_claims(raw_video_claims)
                            print(f"✅ Video claim validation: {len(raw_video_claims)} raw → {len(validated_video_claims)} valid")

                            video_analysis = {
                                "status": "processed",
                                "platform": extraction_result.get("platform"),
                                "credibilityScore": llm_video_result.get("credibilityScore", 50),
                                "verdict": normalize_verdict(llm_video_result.get("verdict", "Medium Risk")),
                                "riskLevel": llm_video_result.get("riskLevel", "medium"),
                                "explanation": llm_video_result.get("explanation", ""),
                                "topicSummary": llm_video_result.get("topicSummary", ""),
                                "framesAnalyzed": extraction_result.get("framesAnalyzed", 0),
                                "visualTextDetected": extraction_result.get("visualTextDetected", False),
                                "ocrText": extraction_result.get("ocrText", []),
                                "validatedClaims": validated_video_claims,
                                "llmAnalysis": {
                                    "riskKeywordsFound": llm_video_result.get("riskKeywordsFound", []),
                                    "claimsIdentified": validated_video_claims,
                                }
                            }

                            # --- Phase D: Evidence Verification (Video Transcript Focus) ---
                            # Use first validated claim for evidence retrieval (better API match rate)
                            v_claim = validated_video_claims[0] if validated_video_claims else None

                            if v_claim:
                                v_evidence = await aggregate_evidence(v_claim)
                                v_verification = await verify_claim_with_evidence(v_claim, v_evidence)
                                video_analysis["knowledgeVerification"] = v_verification
                            
                            store_analysis(video_hash, "video", video_analysis)
                        else:
                            print(f"⚠️ Video extraction failed: {extraction_result.get('error')}")
                            video_analysis = {"status": "skipped", "error": extraction_result.get("error")}
                except Exception as e:
                    print(f"❌ Video analysis failed: {e}")
                    video_analysis = {"status": "skipped", "error": str(e)}

        # ------------------------------------------------------------------ #
        # Step 3: Phases 2, 3, 4, 5 — orchestrated via compute_full_credibility
        #   Internally uses asyncio.gather for fact-check, domain, image auth
        # ------------------------------------------------------------------ #
        final_result = await compute_full_credibility(
            text_analysis,
            image_analysis,
            video_analysis=video_analysis,
            source_url=validated_data.imageUrl or validated_data.videoUrl,
            image_bytes=image_buffer,
        )

        elapsed = round((time.perf_counter() - _start) * 1000)
        print(f"⏱️ Total request time: {elapsed} ms")

        response_data = {
            "success":      True,
            "textAnalysis": text_analysis,
            "imageAnalysis": image_analysis,
            "videoAnalysis": video_analysis,
            "finalResult":  final_result,
            "processingMs": elapsed,
        }

        if text_hash:
            response_data["hash"]   = text_hash
            response_data["reused"] = text_reused
        elif image_hash:
            response_data["hash"]   = image_hash
            response_data["reused"] = image_reused
        elif video_hash:
            response_data["hash"]   = video_hash
            response_data["reused"] = video_reused

        return jsonify(response_data)

    except asyncio.CancelledError:
        # User dismissed the overlay — cancel endpoint called task.cancel()
        elapsed = round((time.perf_counter() - _start) * 1000)
        print(f"🛑 [Job] Analysis cancelled by user after {elapsed} ms (job={job_id})")
        # Must re-raise CancelledError in asyncio; Flask/Hypercorn handles it correctly.
        raise

    except Exception as e:
        print(f"❌ Unexpected error: {e}")
        return jsonify({"success": False, "message": str(e)}), 500

    finally:
        # Always clean up the job registry entry, whether we completed, cancelled, or errored.
        if job_id:
            job_registry.unregister(job_id)
